### ISSUE TITLE
Release schema is from 1.1-dev branch

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/extension_creator#14]
https://github.com/open-contracting/extension_creator/blob/a6eca5e08c0b717df37a729dac497476c5b28257/release-schema/release-schema-1.1.json#L2

The extension creator should use the schema from the latest tagged 1.1 release

**Comment by jpmckinney** [comment]
Closed by 563a95192c7955a2377dc1093862752c5a564f87
