### ISSUE TITLE
JSON generated by 'Download Patch' button is not pretty

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/extension_creator#2]
Clicking the 'Generate Extension' button results in a zip file containing nicely formatted JSON files.

However the release-schema.json file generated by pressing 'Download Patch' is not pretty printed.

![image](https://cloud.githubusercontent.com/assets/19265814/21986406/3bba93c4-dbf7-11e6-937f-04e6d620629d.png)

It would be nice if the 'Download Patch' button also generated well formatted JSON.

**Comment by kindly** [comment]
This is fixed now.  Weird error as if you put the patch in "code" mode in formatted it well, so could not work out what the problem was for a while.
