### ISSUE TITLE
Typo in extension.json

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/extension_creator#3]
There is a typo in the ```extension.json``` in the zip file created by clicking 'Generate Extension' - the ```description``` key is mispelled.

This causes CoVE to crash when you upload a spreadsheet which references the ```extension.json``` in the ```Meta``` tab

**Comment by jpmckinney** [comment]
Fixed in d45486ea (typo was `desription`).

(When reporting typos, it's easier to find the issue if the typo is known, rather than the correction :))
